on:
    workflow_dispatch:

name: Test Analyze Mode External Dependencies

jobs:
  test-falco:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Start Falco
      uses: falcosecurity/falco-actions/start@ddcff83af077b30af70f188ba7b5446c98041446
      with:
        mode: analyze
        verbose: true
        
        # this is meant to trigger a rule, will be based on what the PR did

    - name: Test2
      shell: bash
      run: |
                echo "Test2"
                touch /tmp/pwd
                #cat /home/runner/work/_temp/_runner_file_commands/save_state_*
                
    - name: DNS query
      shell: bash
      run: |
              wget google.com
              sleep 1
              wget example.com
              sleep 1

    - name: Stop Falco
      uses: falcosecurity/falco-actions/stop@ddcff83af077b30af70f188ba7b5446c98041446
      with:
        mode: analyze
        verbose: true

  analyze:
    runs-on: ubuntu-latest
    needs: test-falco
    permissions:
      contents: read
      actions: read
    steps:
    - name: Analyze
      uses: falcosecurity/falco-actions/analyze@ddcff83af077b30af70f188ba7b5446c98041446
      with:
        falco-version: '0.39.0'
        openai-user-prompt: "Pls add remediation steps"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        VT_API_KEY: ${{ secrets.VT_API_KEY }}
